// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// RIC
double RIC(NumericVector x, NumericVector y, int Kr, int Dmax);
RcppExport SEXP _RIC_RIC(SEXP xSEXP, SEXP ySEXP, SEXP KrSEXP, SEXP DmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type Kr(KrSEXP);
    Rcpp::traits::input_parameter< int >::type Dmax(DmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(RIC(x, y, Kr, Dmax));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RIC_RIC", (DL_FUNC) &_RIC_RIC, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_RIC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
